# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Life and Engineering
email: minhduccm90@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is where to share what i'm learning & doing about life and engineering so that when i look back, i find myself getting better everyday.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://minhduccm.github.io" # the base hostname & protocol for your site
github_username:  minhduccm

# Build settings
markdown: kramdown
